// <auto-generated />
using System;
using Atlantis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlantis.Api.Migrations
{
    [DbContext(typeof(AtlantisDbContext))]
    [Migration("20260721191713_NormalizeWorldPersistenceNames")]
    partial class NormalizeWorldPersistenceNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlantis.Api.Data.Entities.EntityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("place_id");

                    b.Property<float>("PositionX")
                        .HasColumnType("real")
                        .HasColumnName("position_x");

                    b.Property<float>("PositionY")
                        .HasColumnType("real")
                        .HasColumnName("position_y");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real")
                        .HasColumnName("position_z");

                    b.Property<DateTime?>("PrivateMessageDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("private_message_delivered_at");

                    b.Property<string>("PrivateMessageSenderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("private_message_sender_id");

                    b.Property<long?>("PrivateMessageSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("private_message_sequence");

                    b.Property<string>("PrivateMessageText")
                        .HasColumnType("text")
                        .HasColumnName("private_message_text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<long?>("UtteranceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("utterance_sequence");

                    b.Property<DateTime?>("UtteranceSpokenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utterance_spoken_at");

                    b.Property<string>("UtteranceText")
                        .HasColumnType("text")
                        .HasColumnName("utterance_text");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ux_entities_world_id_entity_id");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Data.Entities.WorldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_worlds_world_id");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.LedgerEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference_type");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_ledger_entries_account_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_ledger_entries_transaction_id");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_ledger_entries_account_created_at");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_ledger_entries_reference");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.MoneyAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_money_accounts_owner_id");

                    b.HasIndex("OwnerId", "AccountType", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_money_accounts_owner_account_type_currency");

                    b.ToTable("money_accounts", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Data.Entities.EntityEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Data.Entities.WorldEntity", "World")
                        .WithMany("Entities")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.LedgerEntryEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.MoneyAccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Atlantis.Api.Data.Entities.WorldEntity", b =>
                {
                    b.Navigation("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
