// <auto-generated />
using System;
using Atlantis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlantis.Api.Migrations
{
    [DbContext(typeof(AtlantisDbContext))]
    [Migration("20260804204610_RenameOutputDevelopmentPredictionReplayTables")]
    partial class RenameOutputDevelopmentPredictionReplayTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlantis.Api.Data.Entities.EntityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<float?>("GazeDirectionX")
                        .HasColumnType("real")
                        .HasColumnName("gaze_direction_x");

                    b.Property<float?>("GazeDirectionY")
                        .HasColumnType("real")
                        .HasColumnName("gaze_direction_y");

                    b.Property<float?>("GazeDirectionZ")
                        .HasColumnType("real")
                        .HasColumnName("gaze_direction_z");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("place_id");

                    b.Property<float>("PositionX")
                        .HasColumnType("real")
                        .HasColumnName("position_x");

                    b.Property<float>("PositionY")
                        .HasColumnType("real")
                        .HasColumnName("position_y");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real")
                        .HasColumnName("position_z");

                    b.Property<DateTime?>("PrivateMessageDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("private_message_delivered_at");

                    b.Property<string>("PrivateMessageSenderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("private_message_sender_id");

                    b.Property<long?>("PrivateMessageSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("private_message_sequence");

                    b.Property<string>("PrivateMessageText")
                        .HasColumnType("text")
                        .HasColumnName("private_message_text");

                    b.Property<float?>("TorsoFrontX")
                        .HasColumnType("real")
                        .HasColumnName("torso_front_x");

                    b.Property<float?>("TorsoFrontY")
                        .HasColumnType("real")
                        .HasColumnName("torso_front_y");

                    b.Property<float?>("TorsoFrontZ")
                        .HasColumnType("real")
                        .HasColumnName("torso_front_z");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<long?>("UtteranceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("utterance_sequence");

                    b.Property<DateTime?>("UtteranceSpokenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utterance_spoken_at");

                    b.Property<string>("UtteranceText")
                        .HasColumnType("text")
                        .HasColumnName("utterance_text");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ux_entities_world_id_entity_id");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Data.Entities.WorldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_worlds_world_id");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Development.Predictions.Persistence.DevelopmentPredictionRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("context_hash");

                    b.Property<string>("ContextSerialized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context_serialized");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DevelopmentWorldId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("development_world_id");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scenario_id");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<string>("SimulatedCitizenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("simulated_citizen_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentWorldId", "ScenarioId", "SimulatedCitizenId", "SequenceNumber", "ContextHash")
                        .IsUnique()
                        .HasDatabaseName("ux_development_prediction_requests_exact_input");

                    b.ToTable("development_prediction_requests", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Development.Predictions.Persistence.DevelopmentRecordedPredictionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CognitiveOutputSerialized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cognitive_output_serialized");

                    b.Property<string>("ContextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("context_hash");

                    b.Property<string>("DevelopmentWorldId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("development_world_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scenario_id");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<string>("SimulatedCitizenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("simulated_citizen_id");

                    b.Property<string>("WorkerCitizenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_citizen_id");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentWorldId", "ScenarioId", "SimulatedCitizenId", "SequenceNumber", "ContextHash")
                        .IsUnique()
                        .HasDatabaseName("ux_development_recorded_predictions_exact_input");

                    b.ToTable("development_recorded_predictions", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CitizenSponsorshipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("CitizenEntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("citizen_entity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EndReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("FundingAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("funding_account_id");

                    b.Property<string>("SponsorEntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sponsor_entity_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CitizenEntityId")
                        .IsUnique()
                        .HasDatabaseName("ux_citizen_sponsorships_active_citizen")
                        .HasFilter("\"status\" = 2");

                    b.HasIndex("FundingAccountId")
                        .HasDatabaseName("ix_citizen_sponsorships_funding_account");

                    b.HasIndex("SponsorEntityId")
                        .HasDatabaseName("ix_citizen_sponsorships_sponsor");

                    b.ToTable("citizen_sponsorships", null, t =>
                        {
                            t.HasCheckConstraint("ck_citizen_sponsorships_distinct_entities", "\"citizen_entity_id\" <> \"sponsor_entity_id\"");

                            t.HasCheckConstraint("ck_citizen_sponsorships_end_reason", "\"end_reason\" IS NULL OR length(btrim(\"end_reason\")) > 0");

                            t.HasCheckConstraint("ck_citizen_sponsorships_status", "\"status\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_citizen_sponsorships_status_dates", "                (\r\n                    \"status\" = 1\r\n                    AND \"activated_at\" IS NULL\r\n                    AND \"ended_at\" IS NULL\r\n                )\r\n                OR\r\n                (\r\n                    \"status\" = 2\r\n                    AND \"activated_at\" IS NOT NULL\r\n                    AND \"activated_at\" >= \"created_at\"\r\n                    AND \"ended_at\" IS NULL\r\n                )\r\n                OR\r\n                (\r\n                    \"status\" IN (3, 4)\r\n                    AND \"activated_at\" IS NOT NULL\r\n                    AND \"activated_at\" >= \"created_at\"\r\n                    AND \"ended_at\" IS NOT NULL\r\n                    AND \"ended_at\" >= \"activated_at\"\r\n                )");
                        });
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexJobApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid>("CortexJobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_job_definition_id");

                    b.Property<string>("DepositAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deposit_account_id");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("WorkerCitizenId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("worker_citizen_id");

                    b.HasKey("Id");

                    b.HasIndex("CortexJobDefinitionId");

                    b.HasIndex("WorkerCitizenId", "CortexJobDefinitionId")
                        .HasDatabaseName("ix_cortex_job_applications_worker_definition");

                    b.ToTable("cortex_job_applications", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexJobDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompletionInboxId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("completion_inbox_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmployerAccountId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employer_account_id");

                    b.Property<string>("FailureInboxId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("failure_inbox_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Qualifications")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qualifications");

                    b.HasKey("Id");

                    b.HasIndex("EmployerAccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_cortex_job_definitions_employer_name");

                    b.ToTable("cortex_job_definitions", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexJobInboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CortexTaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_task_assignment_id");

                    b.Property<Guid>("CortexTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_task_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InboxId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("inbox_id");

                    b.Property<string>("PayloadSerialized")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_serialized");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_type");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CortexTaskId");

                    b.HasIndex("CortexTaskAssignmentId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_cortex_job_inbox_messages_assignment_type");

                    b.HasIndex("InboxId", "ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_cortex_job_inbox_messages_delivery");

                    b.ToTable("cortex_job_inbox_messages", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexJobScheduleConditionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("condition_type");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<Guid>("CortexJobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_job_definition_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ConditionType")
                        .HasDatabaseName("ix_cortex_job_schedule_conditions_type");

                    b.HasIndex("CortexJobDefinitionId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_cortex_job_schedule_conditions_definition_order");

                    b.ToTable("cortex_job_schedule_conditions", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexTaskAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CortexTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_task_id");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset>("FirstPrimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_primed_at");

                    b.Property<DateTimeOffset>("LastPrimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_primed_at");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("WorkerCitizenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_citizen_id");

                    b.Property<Guid>("WorkerCortexJobQualificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_cortex_job_qualification_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("ix_cortex_task_assignments_assigned_at");

                    b.HasIndex("CortexTaskId")
                        .IsUnique()
                        .HasDatabaseName("ux_cortex_task_assignments_task");

                    b.HasIndex("PaymentTransactionId")
                        .HasDatabaseName("ix_cortex_task_assignments_payment_transaction")
                        .HasFilter("\"payment_transaction_id\" IS NOT NULL");

                    b.HasIndex("WorkerCitizenId")
                        .IsUnique()
                        .HasDatabaseName("ux_cortex_task_assignments_active_worker")
                        .HasFilter("\"status\" = 1");

                    b.HasIndex("WorkerCortexJobQualificationId", "Status")
                        .HasDatabaseName("ix_cortex_task_assignments_qualification_status");

                    b.ToTable("cortex_task_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_cortex_task_assignments_assignment_priming_times", "\"first_primed_at\" >= \"assigned_at\" AND \"last_primed_at\" >= \"first_primed_at\"");

                            t.HasCheckConstraint("ck_cortex_task_assignments_failure_reason", "\"failure_reason\" IS NULL OR length(btrim(\"failure_reason\")) > 0");
                        });
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<string>("CompletionInboxId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("completion_inbox_id");

                    b.Property<Guid>("CortexJobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_job_definition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<string>("FailureInboxId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("failure_inbox_id");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("instructions");

                    b.Property<decimal>("Reward")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("reward");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UnavailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unavailable_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_cortex_tasks_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cortex_tasks_status");

                    b.HasIndex("CortexJobDefinitionId", "Status", "AvailableAt")
                        .HasDatabaseName("ix_cortex_tasks_definition_status_available");

                    b.ToTable("cortex_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_cortex_tasks_reward_positive", "\"reward\" > 0");
                        });
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexTaskResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CortexTaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_task_assignment_id");

                    b.Property<string>("ResultSerialized")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_serialized");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("result_type");

                    b.HasKey("Id");

                    b.HasIndex("CortexTaskAssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_cortex_task_results_assignment");

                    b.ToTable("cortex_task_results", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.LedgerEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference_type");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_ledger_entries_account_id");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_ledger_entries_account_created_at");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_ledger_entries_reference");

                    b.HasIndex("TransactionId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_entries_transaction_id_account_id");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.MoneyAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_money_accounts_owner_id");

                    b.HasIndex("OwnerId", "AccountType", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_money_accounts_owner_account_type_currency");

                    b.ToTable("money_accounts", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.SimulateCitizenPassTaskEntity", b =>
                {
                    b.Property<Guid>("CortexTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_task_id");

                    b.Property<string>("ExternalCitizenId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_citizen_id");

                    b.Property<string>("ExternalRequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_request_id");

                    b.Property<string>("ExternalScenarioId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_scenario_id");

                    b.Property<string>("ExternalWorldId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_world_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("CortexTaskId");

                    b.HasIndex("ExternalCitizenId")
                        .HasDatabaseName("ix_simulate_citizen_pass_tasks_external_citizen");

                    b.HasIndex("ExternalScenarioId")
                        .HasDatabaseName("ix_simulate_citizen_pass_tasks_external_scenario");

                    b.HasIndex("ExternalWorldId", "ExternalRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_simulate_citizen_pass_tasks_world_request");

                    b.ToTable("simulate_citizen_pass_tasks", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.WorkerCortexJobAvailabilityEntity", b =>
                {
                    b.Property<Guid>("WorkerCortexJobQualificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_cortex_job_qualification_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.HasKey("WorkerCortexJobQualificationId");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("ix_worker_cortex_job_availability_is_available");

                    b.ToTable("worker_cortex_job_availability", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.WorkerCortexJobQualificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CortexJobApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_job_application_id");

                    b.Property<Guid>("CortexJobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cortex_job_definition_id");

                    b.Property<string>("DepositAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deposit_account_id");

                    b.Property<DateTimeOffset>("QualifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("qualified_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("WorkerCitizenId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("worker_citizen_id");

                    b.HasKey("Id");

                    b.HasIndex("CortexJobApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ux_worker_cortex_job_qualifications_application");

                    b.HasIndex("CortexJobDefinitionId");

                    b.HasIndex("DepositAccountId")
                        .HasDatabaseName("ix_worker_cortex_job_qualifications_deposit_account");

                    b.HasIndex("WorkerCitizenId", "CortexJobDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ux_worker_cortex_job_qualifications_worker_definition");

                    b.ToTable("worker_cortex_job_qualifications", (string)null);
                });

            modelBuilder.Entity("Atlantis.Api.Data.Entities.EntityEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Data.Entities.WorldEntity", "World")
                        .WithMany("Entities")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CitizenSponsorshipEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.MoneyAccountEntity", "FundingAccount")
                        .WithMany()
                        .HasForeignKey("FundingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FundingAccount");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexJobApplicationEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexJobDefinitionEntity", "CortexJobDefinition")
                        .WithMany()
                        .HasForeignKey("CortexJobDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CortexJobDefinition");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexJobInboxMessageEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexTaskAssignmentEntity", "Assignment")
                        .WithMany()
                        .HasForeignKey("CortexTaskAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexTaskEntity", "CortexTask")
                        .WithMany()
                        .HasForeignKey("CortexTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("CortexTask");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexJobScheduleConditionEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexJobDefinitionEntity", "CortexJobDefinition")
                        .WithMany("ScheduleConditions")
                        .HasForeignKey("CortexJobDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CortexJobDefinition");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexTaskAssignmentEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexTaskEntity", "CortexTask")
                        .WithOne("Assignment")
                        .HasForeignKey("Atlantis.Api.Persistence.Entities.CortexTaskAssignmentEntity", "CortexTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlantis.Api.Persistence.Entities.WorkerCortexJobQualificationEntity", "WorkerCortexJobQualification")
                        .WithMany()
                        .HasForeignKey("WorkerCortexJobQualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CortexTask");

                    b.Navigation("WorkerCortexJobQualification");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexTaskEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexJobDefinitionEntity", "CortexJobDefinition")
                        .WithMany()
                        .HasForeignKey("CortexJobDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CortexJobDefinition");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexTaskResultEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexTaskAssignmentEntity", "Assignment")
                        .WithOne("Result")
                        .HasForeignKey("Atlantis.Api.Persistence.Entities.CortexTaskResultEntity", "CortexTaskAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.LedgerEntryEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.MoneyAccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.SimulateCitizenPassTaskEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexTaskEntity", "CortexTask")
                        .WithOne("SimulateCitizenPassTask")
                        .HasForeignKey("Atlantis.Api.Persistence.Entities.SimulateCitizenPassTaskEntity", "CortexTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CortexTask");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.WorkerCortexJobAvailabilityEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.WorkerCortexJobQualificationEntity", "Qualification")
                        .WithOne("Availability")
                        .HasForeignKey("Atlantis.Api.Persistence.Entities.WorkerCortexJobAvailabilityEntity", "WorkerCortexJobQualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.WorkerCortexJobQualificationEntity", b =>
                {
                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexJobApplicationEntity", "CortexJobApplication")
                        .WithOne("WorkerCortexJobQualification")
                        .HasForeignKey("Atlantis.Api.Persistence.Entities.WorkerCortexJobQualificationEntity", "CortexJobApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlantis.Api.Persistence.Entities.CortexJobDefinitionEntity", "CortexJobDefinition")
                        .WithMany()
                        .HasForeignKey("CortexJobDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CortexJobApplication");

                    b.Navigation("CortexJobDefinition");
                });

            modelBuilder.Entity("Atlantis.Api.Data.Entities.WorldEntity", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexJobApplicationEntity", b =>
                {
                    b.Navigation("WorkerCortexJobQualification");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexJobDefinitionEntity", b =>
                {
                    b.Navigation("ScheduleConditions");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexTaskAssignmentEntity", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.CortexTaskEntity", b =>
                {
                    b.Navigation("Assignment");

                    b.Navigation("SimulateCitizenPassTask");
                });

            modelBuilder.Entity("Atlantis.Api.Persistence.Entities.WorkerCortexJobQualificationEntity", b =>
                {
                    b.Navigation("Availability");
                });
#pragma warning restore 612, 618
        }
    }
}
